talkmultiple,prince,princess,king,throneroom
fallinlove,princess,prince,throneroom
fallinlove,prince,princess,throneroom
hides,maiden,guestroom
move,prince,throneroom,guestroom
talk,princess,king,throneroom
move,princess,throneroom,corridor
move,princess,corridor,guestroom
talk,princess,prince,guestroom
move,princess,guestroom,bedroomprincess
pickup,princess,poison_1,bedroomprincess
move,princess,bedroomprincess,guestroom
talk,prince,princess,guestroom
give,princess,prince,poison_1,guestroom
move,prince,guestroom,dining_room
move,princess,guestroom,dining_room
move,king,throneroom,dining_room
move,maiden,guestroom,kitchen
hides,maiden,kitchen
talkmultiple,prince,princess,king,dining_room
move,prince,dining_room,kitchen
poisons,prince,cup_king,poison_1,kitchen
move,prince,kitchen,dining_room
swaps,maiden,cup_king,cup_prince,kitchen
pickup,maiden,cup_prince,kitchen
move,maiden,kitchen,dining_room
placeon,maiden,cup_prince,table_1,dining_room
drink,prince,cup_prince,dining_room
dies,prince,dining_room
talk,princess,king,dining_room
move,princess,dining_room,prison
marry,king,maiden,dining_room